import 'package:flutter/material.dart';
List images = [
  'assets/image1.jpg',
  'assets/image2.jpg',
  'assets/image00.jpg',
  'assets/image8.jpg',
  'assets/image10.jpg',
  'assets/image18.jpg',
  'assets/image20.jpg',
  'assets/image13.jpg',
  'assets/image9.jpg',
  'assets/image11.jpg',
  'assets/image14.jpg',
  'assets/image15.jpg',
  'assets/image16.jpg',
  'assets/image17.jpg',
  'assets/image21.jpg',
  'assets/image22.jpg',
  'assets/image23.jpg',
  'assets/image24.jpg',
  'assets/image111.jpg',
  'assets/image33.jpg',
  'assets/image12.jpg',
  'assets/image12.jpg',
];